config/routes.rb
Rails.application.routes.draw do
  get 'toukou/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'kumada' => 'homes#kumada'
  post 'toukou' => 'toukou#create'
  get 'toukou' => 'toukou#index'
  get 'toukou/:id' => 'toukou#show', as: 'toukoulist'
  get 'toukou/:id/edit' => 'toukou#edit', as: 'edit_toukoulist'
  patch 'toukou/:id' => 'toukou#update', as: 'update_toukoulist'
  delete 'toukou/:id' => 'toukou#destroy', as: 'destroy_toukoulist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def kumada
    
  end

end

app/controllers/toukou_controller.rb
class ToukouController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    book.save
    redirect_to toukoulist_path(book.id)
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to toukoulist_path(book.id)
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to toukou_path
  end

private
def book_params
  params.require(:book).permit(:title, :body, :image)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/toukou_helper.rb
module ToukouHelper
end

app/views/homes/kumada.html.erb
<h1>ここはTopページです！</h1>
<p>熊田頑張る！</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RensyuApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toukou/edit.html.erb
<h1>変更だよ</h1>
<%= form_with model:@book, url:"/toukou/#{@book.id}", local:true do |f| %>
<h4>タイトル</h4>
<%= f.text_field :title %>
<h4>本文</h4>
<%= f.text_area :body %>
<%= f.submit '保存' %>
<% end %>

app/views/toukou/index.html.erb
<h1>熊田の日記帳</h1>

<% @books.each do |book| %>
<p>タイトル</p>
<span>
  <%= link_to book.title, toukoulist_path(book.id) %>
  </span>
  <p>画像だよ</p>
  <%= attachment_image_tag book, :image, :fill, 100, 100, format: 'jpeg' %>
<% end %>

app/views/toukou/new.html.erb
<h1>熊田の一日</h1>
<%= form_with model: @book, url:'/toukou', local:true do |f| %>
<h4>タイトル</h4>
<%= f.text_field :title %>
<h4>本文</h4>
<%= f.text_area :body %>
<h4></h4>
<%= f.attachment_field :image %>
<%= f.submit '投稿' %>
<% end %>

app/views/toukou/show.html.erb
<h2>内容は</h2>
<p><%= @book.title %></p>
<h2>こちら！！！</h2>
<p><%= @book.body %></p>
<h2></h2>
<%=attachment_image_tag @book, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集はこちら", edit_toukoulist_path(@book.id) %>
<%= link_to "削除はこっち", destroy_toukoulist_path(@book.id), method: :delete, "data-confirm" => "本当に消しちゃうの？" %>